version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: dates_backend
    restart: always
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8008
    ports:
      - 8008:8008
    volumes:
      - ./backend/:/app
    depends_on:
      - db

  db:
    image: postgres:14.0
    container_name: dates_db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

volumes:
  db-data: